### ISSUE TITLE
Правки Main Page

### ISSUE THREAD

**Issue by Jagerente** [GenshinAcademy/GenshinAcademySite#13]

**Comment by Bobrokrot** [comment]
- [x] Ссылка на HoYoLAB в футере: https://www.hoyolab.com/accountCenter/postList?id=37721496
- [x] Ссылку на Хорька добавьте при клике на собственно Хорька.
- [x] Ссылка на Сборник гайдов: https://teletype.in/@genshinacademy/mini-guides
- [x] Новости листать невозможно. Это надо умудриться попасть на тоненький скроллбар, по другому никак. EDIT: А вообще нафиг нам скроллбар. Можно отображать только три последние новости, а остальные только на отдельной странице с новостями "Смотреть все ->".

**Comment by Bobrokrot** [comment]
- [x] Хотели вроде ещё кнопочку в углу, при клике на которую скролл на верх страницы.
- [x] При клике на Инструменты должен быть скролл до раздела с Инструментами. Это в двух местах: в шапке и в кнопке слева от Лизы.
- [x] Аналогично при клике на Новости должен быть скролл на раздел с Новостями. Или хз, наверное, это сразу на отдельную страницу.

**Comment by Jagerente** [comment]
- [x] Избавится от символа `#` в url.
- [x] Поменять во всех строках, переменных, файлах и т.п. `ferret` на `weasel` 
- [x] Починить редирект + добавить аналогичный в шапке на `Guides`
![image](https://user-images.githubusercontent.com/47350537/227875005-6492546c-32d7-4e44-b649-d8501f2203ef.png)
- [x] Добавить иконку. (Есть на макете)

**Comment by Jagerente** [comment]
- [x] Пофиксить кликабельную зону

![Image](https://user-images.githubusercontent.com/47350537/230732969-540511a7-a6b4-4fc9-a8c7-dab4f92043a5.png)

**Comment by Jagerente** [comment]
- [x] Явно указывать якорь в URL например `https://genshin-dev.academy-project.info/#tools` во всех якорях. Иначе, к примеру, при нажатии на Tools из любой страницы не будет произведено перемещение к якорю.

**Comment by Jagerente** [comment]
- [x] Адаптивность согласно макету
- [x] Убрать контакты, вместо них выбор языка.


![Image](https://user-images.githubusercontent.com/47350537/232001733-d4bbd3d1-e27a-4ddd-a877-1d1950c9e644.png)
