### ISSUE TITLE
Правки Weasel Appraiser

### ISSUE THREAD

**Issue by Jagerente** [GenshinAcademy/GenshinAcademySite#2]
# Список:

- [x] Изменить заглушку. Попросим дизайнеров. Название будет uchar.webp, пока что подставить это название
- [x] Отображать стрелочку-якорь только на мобильных устройствах и только после нажатия "Оценить"
- [x] Исправить отображение при width < ~993. .art-stats__art-list { justify-content: space-around; }
- [x] Шрифт грузится неправильно. Скинул в ЛС другой.
- [x] Изменить z-index уведомления и стрелочки.
![image](https://user-images.githubusercontent.com/47350537/215266178-83e7595a-95f5-47db-89a3-a465e0d98c78.png)
- [x] Вместо уведомления делать кнопки, которые это уведомление вызывают disabled.
- [x] Добавить логи. Баллы считаются неправильно. Я сделаю логгер, на будущее везде делать логи это хорошая манера. В .env переменную LOG_LEVEL.
- [x] Изменить название тирлистов соответственно макету:
  - Идеально
  - Отлично
  - Хорошо
  - Сойдёт
- [x] Иконка крио неверная. Скинул в лс.
![image](https://user-images.githubusercontent.com/47350537/215267651-e583a924-b797-41d4-933f-c17d329caf3a.png)
- [x] При выборе Артефакта если кол-во основных характеристик === 1, не открывать дропдаун, выбирать сразу эту характеристику.
- [x] При нажатии на scroll-down или "Оценить", переводить её в состояние scroll-up, которая возвращает сюда и снова становится scroll-down, кнопка "Оценить" имеет функционал scroll-down:
![image](https://user-images.githubusercontent.com/47350537/215267825-831affcf-4641-43ee-9542-bc0861d2fca2.png)

## Баг
- Шаги воспроизведения: 
  - Выбрать любой основной артефакт, у которого несколько характеристик.
  - Выбрать доп. характеристику, которая отличается от текущей основной, но присутствует как возможная.
  - Попытаться выбрать основную характеристику на соответствующую доп. характеристике. 
- [x] Ожидаемый результат:
  - Нельзя выбрать основную характеристику соответствующую доп. характеристике.
- Фактический результат:
  - Можно выбрать и нажать посчитать, однако убрать доп. характеристику уже нельзя.

**Comment by Jagerente** [comment]
- [x] При выборе максимально возможного количества саб статов, лочить остальные.
![image](https://user-images.githubusercontent.com/47350537/215344906-44f9c568-6a86-46ed-ba67-31af542652fb.png)

**Comment by Bobrokrot** [comment]
- [x] Добавить цветовую раскраску для разделов Идеально, Отлично и т.п. (есть в фигме).
- [x] При выводе результатов всегда показывать разделы все разделы Идеально, Отлично и т.п., даже если там 0 персонажей.
- [x] Если выбрана доп. хар-ка, например, Сила атаки % и я затем пытаюсь выбрать основную хар-ку тоже Сила атаки %, то мне не даёт её выбрать. При клике ничего не происходит. Хотелось бы, что бы при клике Сила атаки % всё же выбиралась бы, но тогда доп. хар-ка сбрасывалась.
- [x] При наведении мышкой на портрет персонажа надо выводить имя этого персонажа (новичкам полезно, кто не знает наизусть всех имён персонажей).
- [x] Dropdown сворачивается при клике по области вне его, но не соврачивается при клике в области Результатов.
- [x] Хотелось бы, чтобы dropdown также сворачивался при повторном клике на 1) на уже выбранный элемент 2) на уже выбранный тип артефакта.

**Comment by Bobrokrot** [comment]
- [x] Основной стат Пера: исправить "Сила Атаки" на "Сила атаки".
- [x] Везде: исправить "Сила атака" и "Сила атака %" на "Сила атаки" и "Сила атаки %" соответственно. Везде это в Песках, Кубке, Короне и сабстатах.

**Comment by Bobrokrot** [comment]
- [x] Ещё можно, чтобы при повторном клике на тип артефакта тоже раскрывался список. Сейчас для этого необходимо кликать напрямую на список, а при клике на уже выбранный тип артефакта ничего не происходит.

**Comment by Jagerente** [comment]
- [x] К верхнему дополнение: Закрытие этого списка при клике на любой элемент извне.

**Comment by Bobrokrot** [comment]
- [x] Иконку физ. урона поправить.

![Image](https://user-images.githubusercontent.com/30572380/229343000-c8ae58f7-6253-44ae-b1f5-53b697d8636b.png)

**Comment by Bobrokrot** [comment]
- [x] Ещё лично мне хотелось бы следующую фичу: при двойном клике на сабстат все сабстаты сбрасываются и выбирается этот.

**Comment by Jagerente** [comment]
- [x] Отображение имени при наведении не работает.

**Comment by Bobrokrot** [comment]
- [x] С длинными словами надо что-то сделать.

![Image](https://user-images.githubusercontent.com/30572380/230732137-a187c55c-2af1-402b-978b-7c744a8720d7.png)

**Comment by Bobrokrot** [comment]
- [x] Буква пропущена в англ. Elemental masterY. Это и в сабстатах, и в выборе основной характеристики.
- [x] Надо добавить локализацию для названий тиров (Идеально, отлично, хорошо, сойдёт).

![Image](https://user-images.githubusercontent.com/30572380/230732676-1c6695e0-4992-4a39-9bb0-ef4d84ee494c.png)

**Comment by Bobrokrot** [comment]
Хотелось бы mouse over эффекты добавить везде.

- [x] При наведении мышкой на иконку слота.
- [x] При наведении мышкой на итем в списке основных характеристик.
- [x] При наведении мышкой на кнопку сабстата.

**Comment by Jagerente** [comment]
- [x] При заходе из главной страницы скролит к инструменту, чего быть не должно.

**Comment by Jagerente** [comment]
- [x] Убрать лог 

![Image](https://user-images.githubusercontent.com/47350537/230733461-2356e86c-cb7a-466c-8fd1-2b6a5e8d410e.png)

**Comment by Jagerente** [comment]
- [x] done


![Image](https://user-images.githubusercontent.com/47350537/230776346-44076b32-edbc-42a1-99ee-4ed09f24bc8a.png)

**Comment by Jagerente** [comment]
- [x] Починить ресет сабстатов. На телефоне при быстром выборе статов происходит ресет.

**Comment by Bobrokrot** [comment]
- [x] Если имя состоит из двух слов, второе слово не переносить на новую строку, если любое из двух слов короткое.

![Image](https://user-images.githubusercontent.com/30572380/231571580-e23827bf-8666-4258-bcb5-4380a08f3bf9.png)
![Image](https://user-images.githubusercontent.com/30572380/231571927-7fda3289-624b-442a-bc9d-8fce2bc11217.png)
