### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by Jagerente** [GenshinAcademy/GenshinAcademySite#38]
- [x] Не отображать объект новости и таблиц, если название пустое.
- [x] Меню не отображается в 769px<**ЭТОМ**<992px диапазоне
![image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/47350537/e1fbcdc5-40e0-409f-90ad-1c1d3b93e4b1)
- [x] Добавить `target _blank` к редиректам таблиц.

**Comment by Bobrokrot** [comment]
- [x] После выбора характеристики дродауну требуется целых полсекунды, чтобы исчезнуть.
![image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/30572380/023af143-8e56-4030-a1ae-0f7842731bba)

**Comment by Jagerente** [comment]
- [x] Accept Languages не отправляется.

**Comment by Bobrokrot** [comment]
- [x] У некоторых таблиц нет иконок и нет описаний. Надо, чтобы они соответствующе отображались.
![image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/30572380/4fbbde92-ab90-4d98-93ac-df90461f10ba)

**Comment by Jagerente** [comment]
- [x] Добавить аналитику
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0L5E763TLC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0L5E763TLC');
</script>
```

**Comment by Bobrokrot** [comment]
- [x] С мобилки не вижу ни в каком виде смены языка. У меня при нажатии на пространство слева от меню получается сменить язык (голубым выделяется).
![image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/30572380/21fe5fb6-b340-40d2-8084-8b1ca025bc87)

**Comment by Bobrokrot** [comment]
- [x] На странице таблиц вместо Кэ Цин должна быть вот эта.
![image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/30572380/c2445636-14b3-47e4-8aeb-1a9310ea488a)

**Comment by Jagerente** [comment]
- [x] Стрелочка при наведении сливается с фоном

![Image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/47350537/0a601fca-f4ee-48df-b8d7-786b9c5b0963)

**Comment by Jagerente** [comment]
- [x] Меню не локализовано
![image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/47350537/2a1ba3d8-6bd5-4d7a-826a-9ea46d21f0db)

**Comment by Jagerente** [comment]
- [x] p > h5 ? 😿 Исправить на h1 > p

![Image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/47350537/6ab782cf-9df2-410c-84b3-0605ce3b3a6d)

- [x] h2 > p во всех карточках

![Image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/47350537/68cd8041-09cd-4444-bec1-db2f25b2a53d)

- [x] href сместить на уровень выше. Внутренний <a> заменить на span.


![Image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/47350537/3575dc86-d3a3-4688-9253-e02d512e0acd)

- [x] Добавить aria-label


![Image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/47350537/17f44719-bf9b-4d02-b019-5f57496bfe5d)

**Comment by Jagerente** [comment]
- [x] Исправить адаптивность на мобилках

В рамках https://github.com/GenshinAcademy/GenshinAcademySite/issues/66 ждём уменьшения элементов.

Текущие косяки:
- [x] Меню уехало
- [x] Текст сжимается

![Image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/47350537/f94b9cb5-b06f-45db-9515-f4719650e7e1)

- [x] Выбор статов в 1 столбец, а не 2


![Image](https://github.com/GenshinAcademy/GenshinAcademySite/assets/47350537/053b8ab5-d1fe-462e-9239-897ec5a4e8c1)
